CREATE SEQUENCE  IF NOT EXISTS reservations_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE SEQUENCE  IF NOT EXISTS users_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE SEQUENCE  IF NOT EXISTS wash_type_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE reservations (
  id BIGINT NOT NULL,
   reservation_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   user_id BIGINT,
   wash_type_id BIGINT,
   CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL,
   CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE wash_type (
  id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   required_minutes BIGINT NOT NULL,
   CONSTRAINT wash_type_pkey PRIMARY KEY (id)
);

ALTER TABLE reservations ADD CONSTRAINT reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reservations ADD CONSTRAINT reservations_wash_type_id_fkey FOREIGN KEY (wash_type_id) REFERENCES wash_type (id) ON UPDATE NO ACTION ON DELETE NO ACTION;